# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hsrtDfsyOe6nq6efoJF4JJ9Ju0ew5G8z

Simulação 1: Sequências Elementares em Tempo Discreto
Estudo Dirigido — Parte 1
Este script gera e plota as principais sequências elementares
utilizadas em processamento digital de sinais:
  - Impulso unitário δ[n]
  - Degrau unitário u[n]
  - Rampa r[n]
  - Exponencial real a^n · u[n]
  - Senoide discreta A·cos(ω₀n + φ)
  - Exponencial complexa e^(jω₀n)
"""

import numpy as np
import matplotlib.pyplot as plt

n = np.arange(-10, 11)

# 1. Impulso δ[n]
impulso = np.where(n == 0, 1, 0)

# 2. Degrau u[n]
degrau = np.where(n >= 0, 1, 0)

# 3. Rampa r[n]
rampa = np.where(n >= 0, n, 0)

# 4. Exponencial real a^n
a = 0.8
exponencial = a ** n

# 5. Senoide discreta A*cos(ω0*n + φ)
A = 1
w0 = np.pi / 4   # frequência
phi = np.pi / 6  # fase
senoide = A * np.cos(w0 * n + phi)

# 6. Exponencial complexa e^(jω0n)
exp_complexa = np.exp(1j * w0 * n)

# Plotagem
plt.figure(figsize=(12,10))

plt.subplot(3,2,1)
plt.stem(n, impulso)
plt.title("Impulso δ[n]")

plt.subplot(3,2,2)
plt.stem(n, degrau)
plt.title("Degrau u[n]")

plt.subplot(3,2,3)
plt.stem(n, rampa)
plt.title("Rampa r[n]")

plt.subplot(3,2,4)
plt.stem(n, exponencial)
plt.title("Exponencial real (0.8^n)")

plt.subplot(3,2,5)
plt.stem(n, senoide)
plt.title("Senoide discreta")

# Para exponencial complexa: mostrar parte real e imaginária
plt.subplot(3,2,6)
plt.stem(n, np.real(exp_complexa), linefmt='b-', markerfmt='bo', label='Parte real')
plt.stem(n, np.imag(exp_complexa), linefmt='r-', markerfmt='ro', label='Parte imaginária')
plt.title("Exponencial complexa")
plt.legend()

plt.tight_layout()
plt.show()