# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-1FATXlINFqt840JHFize-Yjs2FOm6QB

Simulação 2: Operações com Sinais Discretos
Estudo Dirigido — Parte 1
Este script demonstra as operações fundamentais sobre sinais discretos:
  - Deslocamento temporal (atraso e avanço)
  - Inversão temporal (reflexão)
  - Escalonamento (decimação)
  - Soma e multiplicação de sinais
"""

import numpy as np
import matplotlib.pyplot as plt

# =========================
# Eixo discreto
# =========================
n = np.arange(-20, 21)

# =========================
# SINAL ORIGINAL
# =========================
x = np.where(n >= 0, 1, 0)  # degrau

# =========================
# OPERAÇÕES NO TEMPO
# =========================

# Atraso: x[n-4]
atraso = np.where((n-4) >= 0, 1, 0)

# Avanço: x[n+3]
avanco = np.where((n+3) >= 0, 1, 0)

# Inversão temporal: x[-n]
inversao = np.where((-n) >= 0, 1, 0)

# =========================
# SENOIDE
# =========================
n_seno = np.arange(0, 40)
w0 = 2*np.pi / 20
seno = np.cos(w0 * n_seno)

# Decimação (fator 2): x[2n]
n_dec = n_seno[::2]
seno_dec = seno[::2]

# =========================
# OPERAÇÕES ENTRE SINAIS
# =========================
x1 = x
x2 = np.where(n == 5, 1, 0)

# Soma
soma = x1 + x2

# Multiplicação
mult = x1 * x2

# =========================
# PLOTAGEM
# =========================
plt.figure(figsize=(12,12))

plt.subplot(4,2,1)
plt.stem(n, x)
plt.title("Sinal original x[n]")

plt.subplot(4,2,2)
plt.stem(n, atraso)
plt.title("Atraso")

plt.subplot(4,2,3)
plt.stem(n, avanco)
plt.title("Avanço")

plt.subplot(4,2,4)
plt.stem(n, inversao)
plt.title("Inversão temporal")

plt.subplot(4,2,5)
plt.stem(n_seno, seno)
plt.title("Senoide original")

plt.subplot(4,2,6)
plt.stem(n_dec, seno_dec)
plt.title("Decimação")

plt.subplot(4,2,7)
plt.stem(n, soma)
plt.title("Soma")

plt.subplot(4,2,8)
plt.stem(n, mult)
plt.title("Multiplicação")

plt.tight_layout()
plt.show()