# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gh_Y-LsjpOOvtXWY44qpSqWQA9HlYE3B

Simulação 3: Energia e Potência de Sinais Discretos
Estudo Dirigido — Parte 1
Este script calcula e demonstra a energia e potência de diferentes sinais discretos:
  - Pulso finito (sinal de energia)
  - Senoide (sinal de potência)
  - Exponencial decrescente (sinal de energia)
  - Rampa (nem energia nem potência)
"""

import numpy as np
import matplotlib.pyplot as plt

# =========================
# Funções
# =========================
def energia(x):
    return np.sum(np.abs(x)**2)

def potencia(x):
    return np.mean(np.abs(x)**2)

def energia_acumulada(x):
    return np.cumsum(np.abs(x)**2)

# =========================
# Eixo discreto
# =========================
n = np.arange(-50, 51)

# =========================
# Sinais
# =========================

# 1. Pulso finito
pulso = np.where((n >= 0) & (n <= 10), 1, 0)

# 2. Senoide
w0 = 2*np.pi/20
seno = np.cos(w0 * n)

# 3. Exponencial decrescente
a = 0.8
exp_dec = np.where(n >= 0, a**n, 0)

# 4. Rampa
rampa = np.where(n >= 0, n, 0)

# =========================
# Energia acumulada
# =========================
E_pulso = energia_acumulada(pulso)
E_seno = energia_acumulada(seno)
E_exp = energia_acumulada(exp_dec)
E_rampa = energia_acumulada(rampa)

# =========================
# Print resultados
# =========================
print("=== Energia e Potência ===\n")

for nome, s in {
    "Pulso": pulso,
    "Senoide": seno,
    "Exponencial": exp_dec,
    "Rampa": rampa
}.items():
    print(f"{nome}: Energia = {energia(s):.2f}, Potência = {potencia(s):.2f}")

# =========================
# Gráficos dos sinais
# =========================
plt.figure(figsize=(12,10))

plt.subplot(4,2,1)
plt.stem(n, pulso)
plt.title("Pulso finito")

plt.subplot(4,2,2)
plt.plot(n, E_pulso)
plt.title("Energia acumulada (Pulso)")

plt.subplot(4,2,3)
plt.stem(n, seno)
plt.title("Senoide")

plt.subplot(4,2,4)
plt.plot(n, E_seno)
plt.title("Energia acumulada (Senoide)")

plt.subplot(4,2,5)
plt.stem(n, exp_dec)
plt.title("Exponencial decrescente")

plt.subplot(4,2,6)
plt.plot(n, E_exp)
plt.title("Energia acumulada (Exponencial)")

plt.subplot(4,2,7)
plt.stem(n, rampa)
plt.title("Rampa")

plt.subplot(4,2,8)
plt.plot(n, E_rampa)
plt.title("Energia acumulada (Rampa)")

plt.tight_layout()
plt.show()