# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEMVK_sfQIBIj6Cd5-KzuYHZb74Bpvql

Simulação 4: Classificação de Sistemas Discretos
Estudo Dirigido — Parte 1
ste script analisa e classifica matematicamente diferentes
sistemas discretos quanto a:
  - Linearidade
  - Invariância no tempo
  - Causalidade
  - Estabilidade BIBO
  - Memória

Sistemas analisados:
  S1: y[n] = 2·x[n] + 3          (não linear, sem memória)
  S2: y[n] = x[n] + x[n-1]       (linear, causal, com memória)
  S3: y[n] = n·x[n]              (linear, variante no tempo)
  S4: y[n] = x[n+1] - x[n]      (linear, não causal)
  S5: y[n] = x²[n]              (não linear, sem memória)
  S6: acumulador Σ x[k]          (linear, instável)
"""

import numpy as np
import matplotlib.pyplot as plt

# Configurações do tempo discreto
n = np.arange(-5, 15)
x = np.where(n >= 0, 1.0, 0.0)  # Degrau unitário como entrada padrão
x_imp = np.where(n == 0, 1.0, 0.0) # Impulso unitário

def analyze_systems():
    # Definição dos Sistemas
    systems = {
        "S1: y[n] = 2x[n] + 3": lambda x, n: 2*x + 3,
        "S2: y[n] = x[n] + x[n-1]": lambda x, n: x + np.roll(x, 1),
        "S3: y[n] = n*x[n]": lambda x, n: n * x,
        "S4: y[n] = x[n+1] - x[n]": lambda x, n: np.roll(x, -1) - x,
        "S5: y[n] = x[n]²": lambda x, n: x**2,
        "S6: y[n] = Accumulator": lambda x, n: np.cumsum(x)
    }

    fig, axes = plt.subplots(3, 2, figsize=(12, 10))
    axes = axes.flatten()

    for i, (name, sys_func) in enumerate(systems.items()):
        y = sys_func(x, n)

        # Plotagem
        axes[i].stem(n, y, basefmt=" ", linefmt='b', markerfmt='bo')
        axes[i].set_title(name)
        axes[i].grid(True, linestyle='--', alpha=0.7)
        axes[i].set_ylabel('y[n]')
        axes[i].set_xlabel('n')

    plt.tight_layout()
    plt.show()

analyze_systems()