# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f8H6w5AcWaVabj896hE3OBjTvanh0uoO
"""

import numpy as np
import matplotlib.pyplot as plt

# --- Configurações Iniciais ---
fs = 1000  # Frequência de amostragem (Hz)
t_final = 1.0  # Duração de 1 segundo
n = np.arange(0, int(fs * t_final)) # Vetor de amostras discretas
t = n / fs  # Vetor de tempo

# --- 1. Geração das Componentes ---
f1, A1 = 30, 1.0    # Fundamental
f2, A2 = 60, 0.5    # 2ª Harmônica (Desalinhamento)
ruido = 0.2 * np.random.randn(len(n)) # Ruído Branco

# Componente Transitória (Impacto de falha - decaimento exponencial)
transiente = 1.5 * np.exp(-50 * (t - 0.5)) * np.sin(2 * np.pi * 100 * (t - 0.5))
transiente[t < 0.5] = 0 # O impacto ocorre em 0.5s

# Sinal Composto Total
x_n = A1 * np.sin(2 * np.pi * f1 * t) + A2 * np.sin(2 * np.pi * f2 * t) + transiente + ruido

# --- 2. Processamento: Filtro de Média Móvel ---
# Um filtro FIR simples: y[n] = (1/M) * sum(x[n-k]) de k=0 até M-1
M = 10
y_n = np.convolve(x_n, np.ones(M)/M, mode='same')

# --- 3. Análise de Energia e Potência ---
energia = np.sum(np.abs(x_n)**2)
potencia = energia / len(x_n)

# --- 4. Visualização ---
plt.figure(figsize=(12, 8))

plt.subplot(3, 1, 1)
plt.plot(t, x_n, label='Sinal Bruto (Vibração)')
plt.title('Sinal Discreto do Sensor de Vibração (1800 RPM)')
plt.ylabel('Aceleração [g]')
plt.legend()

plt.subplot(3, 1, 2)
plt.plot(t, y_n, color='orange', label='Sinal Filtrado (Média Móvel)')
plt.title(f'Aplicação de Filtro de Média Móvel (M={M})')
plt.ylabel('Amplitude')
plt.legend()

# Visualização no domínio da frequência (DFT/FFT)
freqs = np.fft.rfftfreq(len(n), 1/fs)
fft_values = np.abs(np.fft.rfft(x_n))
plt.subplot(3, 1, 3)
plt.plot(freqs, fft_values)
plt.title('Espectro de Frequência (Identificação de Falhas)')
plt.xlabel('Frequência [Hz]')
plt.ylabel('Magnitude')
plt.xlim(0, 150)

plt.tight_layout()
plt.show()

print(f"Energia do Sinal: {energia:.2f}")
print(f"Potência Média: {potencia:.2f}")